name: floviz

services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.21.1
    ports:
      - 6789:8080
    volumes:
      - ./geoserver/geoserver_data:/opt/geoserver_data
    environment:
      INSTALL_EXTENSIONS: true
      STABLE_EXTENSIONS: "wps,ysld,wps-download"
      
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./frontend-old/docs/:/var/www/:ro
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro 
    networks:
      - internal-network

volumes:
  geoserver-volume:

networks:
  internal-network: {}